wandb_version: 1

_wandb:
  desc: null
  value:
    python_version: 3.10.14
    cli_version: 0.17.1
    framework: huggingface
    huggingface_version: 4.39.3
    is_jupyter_run: true
    is_kaggle_kernel: false
    start_time: 1718197877
    t:
      1:
      - 1
      - 11
      - 49
      - 55
      - 71
      - 105
      2:
      - 1
      - 11
      - 49
      - 55
      - 71
      - 105
      3:
      - 2
      - 23
      4: 3.10.14
      5: 0.17.1
      6: 4.39.3
      8:
      - 1
      - 4
      - 5
      13: darwin-arm64
