wandb_version: 1

_wandb:
  desc: null
  value:
    python_version: 3.10.14
    cli_version: 0.17.1
    framework: huggingface
    huggingface_version: 4.41.2
    is_jupyter_run: true
    is_kaggle_kernel: false
    start_time: 1718207486
    t:
      1:
      - 1
      - 11
      - 49
      - 55
      - 71
      - 105
      3:
      - 23
      4: 3.10.14
      5: 0.17.1
      6: 4.41.2
      8:
      - 1
      - 5
      13: darwin-arm64
